FROM node:22-alpine
RUN apk update && apk add openssl

# Install pnpm globally
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /usr/src/app

RUN apk add --no-cache openssl

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./packages ./packages

COPY ./apps/client ./apps/client

RUN pnpm install --verbose

COPY . .

RUN npm install -g turbo

EXPOSE 3001
CMD ["pnpm", "run", "start:client"]
